services:
  achievement-watcher-api:
    container_name: achievement-watcher-api
    restart: unless-stopped
    ports:
      - "3888:80"
    volumes:
      - ${DATA_PATH}/steam/data:/app/data
    environment:
      - NODE_ENV=production
    image: ghcr.io/bbbreaddd/steam_api_proxy:latest
